In [226]:
from datetime import datetime as dt
import folium
import os
import sys
sys.path.insert(0, '..')
import tarfile
import requests
from utils import DataLoader


dl = DataLoader()
dfs = dl.fetch_virus_data()

In [227]:
dl.df_zip

{'case-hosp-death':    DATE_OF_INTEREST  NEW_COVID_CASE_COUNT  HOSPITALIZED_CASE_COUNT  \
 0            3/2/20                     1                      4.0
 1            3/3/20                     2                      3.0
 2            3/4/20                    10                      5.0
 3            3/5/20                     2                      4.0
 4            3/6/20                     8                      5.0
 5            3/7/20                    13                      9.0
 6            3/8/20                    20                     12.0
 7            3/9/20                    53                     24.0
 8           3/10/20                    70                     38.0
 9           3/11/20                   156                     56.0
 10          3/12/20                   356                     62.0
 11          3/13/20                   612                    121.0
 12          3/14/20                   628                    147.0
 13          3/15/20                  1006                    189.0
 14          3/16/20                  2032                    301.0
 15          3/17/20                  2332                    325.0
 16          3/18/20                  2786                    393.0
 17          3/19/20                  3459                    486.0
 18          3/20/20                  3696                    553.0
 19          3/21/20                  2177                    549.0
 20          3/22/20                  2048                    572.0
 21          3/23/20                  3085                    782.0
 22          3/24/20                  3508                    759.0
 23          3/25/20                  3814                    823.0
 24          3/26/20                  3916                    840.0
 25          3/27/20                  3546                    862.0
 26          3/28/20                  2361                    715.0
 27          3/29/20                  2590                    809.0
 28          3/30/20                  4042                    896.0
 29          3/31/20                  3096                    694.0
 30           4/1/20                  2761                    567.0
 31           4/2/20                  2037                    113.0
 32           4/3/20                    63                      NaN

     DEATH_COUNT
 0           NaN
 1           NaN
 2           NaN
 3           NaN
 4           NaN
 5           NaN
 6           NaN
 7           NaN
 8           NaN
 9           1.0
 10          NaN
 11          NaN
 12          2.0
 13          5.0
 14          9.0
 15          7.0
 16         21.0
 17         24.0
 18         43.0
 19         33.0
 20         44.0
 21         75.0
 22         81.0
 23        103.0
 24        149.0
 25        160.0
 26        182.0
 27        192.0
 28        191.0
 29        204.0
 30        181.0
 31        131.0
 32         21.0  , 'summary':                  Cases:               56289
 0  Total hospitalized*:               11739
 1               Deaths:                1867
 2                As of:  04/03/2020, 5:00pm, 'by-sex':         SEX_GROUP  COVID_CASE_RATE  HOSPITALIZED_CASE_RATE  DEATH_RATE
 0          Female           581.32                  108.47       16.07
 1            Male           765.66                  173.99       28.93
 2  Citywide total           670.21                  139.77       22.23, 'boro':    BOROUGH_GROUP  COVID_CASE_COUNT  COVID_CASE_RATE
 0          BRONX             10765           729.11
 1       BROOKLYN             15327           564.77
 2      MANHATTAN              8222           439.68
 3         QUEENS             18823           759.11
 4  STATEN ISLAND              3117           612.60
 5       Citywide             56289              NaN, 'by-age':             AGE_GROUP  COVID_CASE_RATE  HOSPITALIZED_CASE_RATE  DEATH_RATE
 0          0-17 years            57.21                    5.33        0.06
 1         18-44 years           665.76                   58.23        3.26
 2         45-64 years           971.33                  212.45       21.50
 3         65-75 years          1010.42                  367.89       65.94
 4  75 and older years          1043.74                  501.85      155.95
 5      Citywide total           670.21                  139.77       22.23, 'tests-by-zcta':      MODZCTA  Positive  Total  zcta_cum.perc_pos zip_code
 0        NaN      4473   4477              99.91      NaN
 1    10001.0       136    304              44.74    10001
 2    10002.0       317    651              48.69    10002
 3    10003.0       191    438              43.61    10003
 4    10004.0        19     42              45.24    10004
 5    10005.0        28     94              29.79    10005
 6    10006.0         7     26              26.92    10006
 7    10007.0        28     75              37.33    10007
 8    10009.0       236    548              43.07    10009
 9    10010.0       118    336              35.12    10010
 10   10011.0       255    549              46.45    10011
 11   10012.0        77    209              36.84    10012
 12   10013.0       120    265              45.28    10013
 13   10014.0       163    347              46.97    10014
 14   10016.0       295    661              44.63    10016
 15   10017.0        59    173              34.10    10017
 16   10018.0        97    211              45.97    10018
 17   10019.0       226    520              43.46    10019
 18   10021.0       258    672              38.39    10021
 19   10022.0       148    400              37.00    10022
 20   10023.0       231    583              39.62    10023
 21   10024.0       255    731              34.88    10024
 22   10025.0       327    892              36.66    10025
 23   10026.0       166    363              45.73    10026
 24   10027.0       224    504              44.44    10027
 25   10028.0       220    550              40.00    10028
 26   10029.0       373    807              46.22    10029
 27   10030.0       135    247              54.66    10030
 28   10031.0       288    498              57.83    10031
 29   10032.0       389    670              58.06    10032
 ..       ...       ...    ...                ...      ...
 148  11377.0       515    831              61.97    11377
 149  11378.0       198    353              56.09    11378
 150  11379.0       252    456              55.26    11379
 151  11385.0       606   1021              59.35    11385
 152  11411.0       213    303              70.30    11411
 153  11412.0       348    554              62.82    11412
 154  11413.0       393    618              63.59    11413
 155  11414.0       220    401              54.86    11414
 156  11415.0       185    313              59.11    11415
 157  11416.0       161    248              64.92    11416
 158  11417.0       230    381              60.37    11417
 159  11418.0       293    474              61.81    11418
 160  11419.0       261    450              58.00    11419
 161  11420.0       339    565              60.00    11420
 162  11421.0       280    452              61.95    11421
 163  11422.0       303    470              64.47    11422
 164  11423.0       248    382              64.92    11423
 165  11426.0       141    267              52.81    11426
 166  11427.0       233    400              58.25    11427
 167  11428.0       167    252              66.27    11428
 168  11434.0       536    803              66.75    11434
 169  11432.0       448    711              63.01    11432
 170  11433.0       226    344              65.70    11433
 171  11435.0       409    684              59.80    11435
 172  11436.0       137    205              66.83    11436
 173  11691.0       616    926              66.52    11691
 174  11692.0       155    246              63.01    11692
 175  11693.0       116    189              61.38    11693
 176  11694.0       188    349              53.87    11694
 177  11697.0        30     71              42.25    11697

 [178 rows x 5 columns]}

In [136]:

    
    folium.Marker(
        location=[lat, lng],
        popup=f'total: {total}\npositive: {positive}',
        tooltip = k
    ).add_to(ny)
ny

IndentationError: unexpected indent (<ipython-input-136-7ae2eb59eb1c>, line 3)